version: '2'

services:
  app:
    image: abakpress/ruby:$RUBY_IMAGE_TAG
    environment:
      - SSH_AUTH_SOCK=/ssh/auth/sock
      - BUNDLE_PATH=/bundle/$DOCKER_RUBY_VERSION
      - BUNDLE_CONFIG=/app/.bundle/config
      - TEST_DB_HOST=db
      - TEST_DB_NAME=docker
      - TEST_DB_USERNAME=postgres
    command: bash
    depends_on:
      - db

  db:
    image: abakpress/postgres:9.3
    environment:
      - POSTGRES_DB=docker
